version: '2'
services:
  mock:
    image: mock_service
    container_name: mock
    env_file: .env
    volumes:
      - ".:/app"
  client:
    image: mock_service
    container_name: client
    depends_on:
      - mock
    command: bash -c "sleep 3; curl http://mock:${PORT}/profile"
